/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietHoaDon_dao;
import DAO.HoaDon_dao;
import DAO.Sach_dao;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import POJO.ChiTietHoaDon_pojo;
import POJO.HoaDon_pojo;
import POJO.Sach_pojo;
import POJO.XuatHoaDon_pojo;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;

/**
 *
 * @author ThinhDN
 */
public class HoaDon_gui extends javax.swing.JInternalFrame {

    /**
     * Creates new form HoaDon
     */
    DefaultTableModel dtmHD = new DefaultTableModel();
    DefaultTableModel dtmCT = new DefaultTableModel();
    DefaultComboBoxModel s;

    public HoaDon_gui() {
        this.setTitle("Hóa đơn");
        initComponents();
        this.setSize(1920, 1080);
        String[] tieuDeHD = {"Mã hóa đơn", "Ngày lập", "Tổng tiền", "Mã KH", "Mã NV", "Tình trạng"};
        String[] tieuDeCT = {"Mã hóa đơn", "Mã sách", "Số lượng"};
        dtmHD.setColumnIdentifiers(tieuDeHD);
        dtmCT.setColumnIdentifiers(tieuDeCT);
        hienthiHD();
        hienthiCT();
        btnLuuHD.setEnabled(false);
        btnLuuCTHD.setEnabled(false);
        txtTongTien.setEnabled(false);
        txtTinhTrang.setEnabled(false);
        txtMaS.setEnabled(false);
        loadCBOS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnThemHD = new javax.swing.JButton();
        btnLuuHD = new javax.swing.JButton();
        btnXoaHD = new javax.swing.JButton();
        btnTinhTongTien = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        btnXuatHoaDon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        btnXoaCTHD = new javax.swing.JButton();
        btnLuuCTHD = new javax.swing.JButton();
        btnThemCTHD = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtSoLuongM = new javax.swing.JSpinner();
        txtMaS = new javax.swing.JTextField();
        cboS = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCT = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1900, 1070));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("HÓA ĐƠN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN HOÁ ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã Hóa Đơn :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mã khách hàng:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tổng Tiền :");

        btnThemHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThemHD.setText("Thêm");
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        btnLuuHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLuuHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luu.png"))); // NOI18N
        btnLuuHD.setText("Lưu");
        btnLuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHDActionPerformed(evt);
            }
        });

        btnXoaHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoaHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoaHD.setText("Xóa");
        btnXoaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHDActionPerformed(evt);
            }
        });

        btnTinhTongTien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTinhTongTien.setText("Tính tổng tiền");
        btnTinhTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTongTienActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tình trạng:");

        btnXuatHoaDon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXuatHoaDon.setText("Xuất hoá đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaHD)
                        .addGap(236, 236, 236)
                        .addComponent(btnXuatHoaDon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(btnTinhTongTien)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLuuHD)
                        .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTinhTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT HOÁ ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Mã Sách :");

        label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label.setText("Số Lượng Mua :");

        btnXoaCTHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoaCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoaCTHD.setText("Xóa");
        btnXoaCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTHDActionPerformed(evt);
            }
        });

        btnLuuCTHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLuuCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luu.png"))); // NOI18N
        btnLuuCTHD.setText("Lưu");
        btnLuuCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTHDActionPerformed(evt);
            }
        });

        btnThemCTHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThemCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThemCTHD.setText("Thêm");
        btnThemCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTHDActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/timkiem.png"))); // NOI18N
        btnTim.setText("Tìm sách");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        txtSoLuongM.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        txtMaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSActionPerformed(evt);
            }
        });

        cboS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoLuongM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnTim)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cboS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThemCTHD)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuuCTHD)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaCTHD)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(703, 703, 703))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(txtSoLuongM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemCTHD)
                    .addComponent(btnLuuCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tbCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCT);

        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbHD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(826, 826, 826)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTMouseClicked
        // TODO add your handling code here:
        int row = tbCT.getSelectedRow();
        txtMaS.setText((String) String.valueOf(tbCT.getValueAt(row, 1)));
        txtSoLuongM.setValue(Integer.parseInt(String.valueOf(tbCT.getValueAt(row, 2))));
        btnLuuCTHD.setEnabled(true);
    }//GEN-LAST:event_tbCTMouseClicked

    private void btnLuuCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTHDActionPerformed
        // TODO add your handling code here:
        if (txtMaHD.getText().isEmpty() || txtMaKH.getText().isEmpty() || txtMaS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Được Để Trống Thông Tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else if (isNumeric(txtSoLuongM.getValue().toString())) {
            JOptionPane.showMessageDialog(this, " Số Lượng Mua Không được nhập chữ ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int sl = (int) txtSoLuongM.getValue();
            int slc = Sach_dao.laySLSach(txtMaS.getText());
            if (sl > slc) {
                JOptionPane.showMessageDialog(this, "Số lượng mua nhiều hơn số lượng sách còn lại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (ChiTietHoaDon_dao.ktraCTHDS(txtMaHD.getText(), txtMaS.getText())) {
                    ChiTietHoaDon_pojo ct = new ChiTietHoaDon_pojo(txtMaHD.getText(), txtMaS.getText(), Integer.parseInt(txtSoLuongM.getValue().toString()));
                    boolean suaHD = ChiTietHoaDon_dao.suaCTHD(ct);
                    if (suaHD == true) {
                        JOptionPane.showMessageDialog(this, "Sửa chi tiết hóa đơn thành công");
                        hienthiCT();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa chi tiết hóa đơn thất bại");
                    }
                } else {
                    boolean ktraMaHD = HoaDon_dao.ktraMaHD(txtMaHD.getText());
                    if (ktraMaHD == true) {
                        ChiTietHoaDon_pojo ct = new ChiTietHoaDon_pojo(txtMaHD.getText(), txtMaS.getText(), Integer.parseInt(txtSoLuongM.getValue().toString()));
                        boolean themHD = ChiTietHoaDon_dao.themCTHD(ct);
                        if (themHD == true) {
                            JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thành công");
                            hienthiCT();
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thất bại");
                        }
                    } else {
                        boolean themHD = HoaDon_dao.themHD(txtMaHD.getText(), txtMaKH.getText());
                        if (themHD == true) {
                            ChiTietHoaDon_pojo ctm = new ChiTietHoaDon_pojo(txtMaHD.getText(), txtMaS.getText(), Integer.parseInt(txtSoLuongM.getValue().toString()));
                            boolean themHDM = ChiTietHoaDon_dao.themCTHD(ctm);
                            if (themHDM == true) {
                                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thành công");
                                hienthiCT();
                            } else {
                                JOptionPane.showMessageDialog(this, "Thêm chi tiết hóa đơn thất bại");
                            }
                            JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công");
                            hienthiHD();
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm hóa thất bại");
                        }
                    }
                }
                btnLuuCTHD.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnLuuCTHDActionPerformed

    private void btnThemCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTHDActionPerformed
        // TODO add your handling code here:
        txtMaS.requestFocus();
        btnLuuCTHD.setEnabled(true);
    }//GEN-LAST:event_btnThemCTHDActionPerformed

    private void btnXoaCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTHDActionPerformed
        // TODO add your handling code here:
        try {
            int row = tbCT.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Xóa ");
                return;
            } else {
                int n = JOptionPane.showConfirmDialog(this,"Chắc Xóa Chưa" , "Thông Báo", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.NO_OPTION) {
                    return;
                } else {
                    ChiTietHoaDon_dao.xoaCTHD(txtMaHD.getText(), txtMaS.getText());
                    hienthiCT();
                    JOptionPane.showMessageDialog(this, "Xoá Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            hienthiCT();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaCTHDActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        TimSach_gui f = new TimSach_gui();
        f.setVisible(true);
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnTinhTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTinhTongTienActionPerformed

    private void btnXoaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHDActionPerformed
        // TODO add your handling code here:
        try {
            int row = tbHD.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Xóa ");
                return;
            } else {
                int n = JOptionPane.showConfirmDialog(this,"Chắc Xóa Chưa","Thông Báo", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.NO_OPTION) {
                    return;
                } else {
                    HoaDon_dao.xoaHD(txtMaHD.getText());
                    hienthiHD();
                    JOptionPane.showMessageDialog(this, "Xoá Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            hienthiHD();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaHDActionPerformed

    private void btnLuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHDActionPerformed
        // TODO add your handling code here:
        if (txtMaHD.getText().isEmpty() || txtMaKH.getText().isEmpty() || txtTinhTrang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Được Để Trống Thông Tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (HoaDon_dao.ktraMaHD(txtMaHD.getText())) {
                boolean suaHD = HoaDon_dao.suaHD(txtMaHD.getText(), txtMaKH.getText(), txtTinhTrang.getText());
                if (suaHD) {
                    JOptionPane.showMessageDialog(this, "Sửa hóa đơn thành công");
                    hienthiHD();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa hóa đơn thất bại");
                }
            } else {
                boolean themHD = HoaDon_dao.themHD(txtMaHD.getText(), txtMaKH.getText());
                if (themHD) {
                    JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công");
                    hienthiHD();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm hóa đơn thất bại");
                }
            }
            btnLuuHD.setEnabled(false);
        }
    }//GEN-LAST:event_btnLuuHDActionPerformed

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        // TODO add your handling code here:
        txtMaHD.setText("");
        txtMaKH.setText("");
        txtTongTien.setText("");
        txtMaHD.requestFocus();
        btnLuuHD.setEnabled(true);
    }//GEN-LAST:event_btnThemHDActionPerformed

    private void tbHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseClicked
        // TODO add your handling code here:
        btnLuuHD.setEnabled(true);
        int row = tbHD.getSelectedRow();
        txtMaHD.setText((String) String.valueOf(tbHD.getValueAt(row, 0)));
        txtMaKH.setText((String) String.valueOf(tbHD.getValueAt(row, 3)));
        txtTongTien.setText((String) String.valueOf(tbHD.getValueAt(row, 2)));
        txtTinhTrang.setText((String) String.valueOf(tbHD.getValueAt(row, 5)));
        hienthiCT();
    }//GEN-LAST:event_tbHDMouseClicked

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int TongSL = 0;
            String maHD = txtMaHD.getText();
            if (maHD == "") {
                JOptionPane.showMessageDialog(this, "Nhập mã hoá đơn muốn xuất!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            FileWriter fw = new FileWriter("HoaDon_" + maHD + ".txt");
            BufferedWriter bw = new BufferedWriter(fw);

            ArrayList<XuatHoaDon_pojo> dshd = HoaDon_dao.xuatHoaDon(maHD);
            for (XuatHoaDon_pojo hd : dshd) {
                bw.write("               Cửa hàng nhà sách HUFI");
                bw.newLine();
                bw.write("Đ/c: 140, Lê Trọng Tấn, Tây Thạnh, Tân Phú, TPHCM");
                bw.newLine();
                bw.write("Mã hoá đơn: " + hd.getMaHD());
                bw.newLine();
                SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
                String ngaylap = formater.format(hd.getNgayLap());
                bw.write("Ngày lập: " + ngaylap);
                bw.newLine();
                bw.write("Mô tả: ");
                bw.newLine();
                bw.write("=================================================");
                bw.newLine();
                break;
            }
            for (XuatHoaDon_pojo hd : dshd) {
                TongSL = TongSL + hd.getSoLuongMua();
                bw.write("" + hd.getTenSach() + " | " + hd.getSoLuongMua() + " | " + hd.getDonGia());
                bw.newLine();
            }
            for (XuatHoaDon_pojo hd : dshd) {
                bw.write("-------------------------------------------------");
                bw.newLine();
                bw.write("Tổng số lượng: " + TongSL);
                bw.newLine();
                bw.write("Tổng tiền: " + hd.getTongTien());
                bw.newLine();
                bw.write("=================================================");
                bw.newLine();
                bw.write("Xin cám ơn quý khách!");

                bw.close();
                fw.close();
                break;
            }
            JOptionPane.showMessageDialog(this, "Xuất hoá đơn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Xuất hoá đơn thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void txtMaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSActionPerformed

    private void cboSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSActionPerformed
        // TODO add your handling code here:
        int row = cboS.getSelectedIndex();
        txtMaS.setText(cboS.getItemAt(row));
    }//GEN-LAST:event_cboSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuCTHD;
    private javax.swing.JButton btnLuuHD;
    private javax.swing.JButton btnThemCTHD;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTinhTongTien;
    private javax.swing.JButton btnXoaCTHD;
    private javax.swing.JButton btnXoaHD;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JComboBox<String> cboS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label;
    private javax.swing.JTable tbCT;
    private javax.swing.JTable tbHD;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaS;
    private javax.swing.JSpinner txtSoLuongM;
    private javax.swing.JTextField txtTinhTrang;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void hienthiHD() {
        ArrayList<HoaDon_pojo> dsHD = HoaDon_dao.layDanhSachHoaDon();
        dtmHD.setRowCount(0);
        for (HoaDon_pojo pb : dsHD) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaHD());
            v.add(pb.getNgayLap());
            v.add(pb.getTongTien());
            v.add(pb.getMaKH());
            v.add(pb.getMaNV());
            v.add(pb.getTinhTrang());
            dtmHD.addRow(v);
        }
        tbHD.setModel(dtmHD);
    }

    private void hienthiCT() {
        ArrayList<ChiTietHoaDon_pojo> dsHD = ChiTietHoaDon_dao.layDanhSachChiTiet(txtMaHD.getText());
        dtmCT.setRowCount(0);
        for (ChiTietHoaDon_pojo pb : dsHD) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaHD());
            v.add(pb.getMaS());
            v.add(pb.getSoLuong());
            dtmCT.addRow(v);
        }
        tbCT.setModel(dtmCT);
    }

    private void loadCBOS() {
        s = (DefaultComboBoxModel) cboS.getModel();
        ArrayList<Sach_pojo> dsKH = Sach_dao.layDanhSachSach();
        for (Sach_pojo pb : dsKH) {
            cboS.addItem(pb.getMaS());
        }
    }

    public static boolean isNumeric(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }

    public static boolean isChar(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            } else {
                return true;
            }
        }
        return true;
    }
}
