/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.KhachHang_dao;
import DAO.SQLServerDataProvider;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import POJO.KhachHang_pojo;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinhDN
 */
public class KhachHang_gui extends javax.swing.JInternalFrame {

    /**
     * Creates new form KhachHang
     */
    DefaultTableModel dtmKH = new DefaultTableModel();

    public KhachHang_gui() {
        this.setTitle("Khách hàng");
        initComponents();
        this.setSize(1920, 1030);
        String[] tieuDeKH = {"Mã khách hàng", "Tên kh", "Số điện thoại", "Email", "Điểm"};
        dtmKH.setColumnIdentifiers(tieuDeKH);
        hienthiKH();
        btnLuu.setEnabled(false);
        txt_capBac.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenKh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXuatThe = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_capBac = new javax.swing.JTextField();
        btn_timKiemTheoMa = new javax.swing.JButton();
        btn_Tra = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKH = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("LẬP THẺ THÀNH VIÊN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN KHÁCH HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã khách hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("SĐT:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Điểm:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Họ tên KH:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Email:");

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luu.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXuatThe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXuatThe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thoat (1).jpg"))); // NOI18N
        btnXuatThe.setText("Xuất thẻ");
        btnXuatThe.setPreferredSize(new java.awt.Dimension(129, 38));
        btnXuatThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatTheActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Cấp Bậc:");

        txt_capBac.setForeground(new java.awt.Color(51, 51, 51));

        btn_timKiemTheoMa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_timKiemTheoMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btn_timKiemTheoMa.setText("Tìm Kiếm");
        btn_timKiemTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemTheoMaActionPerformed(evt);
            }
        });

        btn_Tra.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_Tra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/timkiem.png"))); // NOI18N
        btn_Tra.setText("Tra ");
        btn_Tra.setPreferredSize(new java.awt.Dimension(101, 38));
        btn_Tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMail, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtTenKh)
                            .addComponent(txt_capBac)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXuatThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_timKiemTheoMa)
                        .addGap(41, 41, 41)
                        .addComponent(btn_Tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txt_capBac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_timKiemTheoMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatThe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tbKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKH);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/khachhang.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/khachhang1 (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1049, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(729, 729, 729))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKHMouseClicked
        // TODO add your handling code here:
        int row = tbKH.getSelectedRow();
        txtMaKH.setText((String) String.valueOf(tbKH.getValueAt(row, 0)));
        txtTenKh.setText((String) String.valueOf(tbKH.getValueAt(row, 1)));
        txtSDT.setText((String) String.valueOf(tbKH.getValueAt(row, 2)));
        txtMail.setText((String) String.valueOf(tbKH.getValueAt(row, 3)));
        txtDiem.setText((String) String.valueOf(tbKH.getValueAt(row, 4)));
        int diem = Integer.valueOf(txtDiem.getText());
        txt_capBac.setText(kiemTraCapBacTheThanhVien(diem));
    }//GEN-LAST:event_tbKHMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtMaKH.setText("");
        txtTenKh.setText("");
        txtSDT.setText("");
        txtMail.setText("");
        txtDiem.setText("");
        txtMaKH.requestFocus();
        btnLuu.setEnabled(true);
        txtTenKh.setEnabled(true);
        txtSDT.setEnabled(true);
        txtMail.setEnabled(true);
        txtDiem.setEnabled(true);
        hienthiKH();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        try {
            String maKH = txtMaKH.getText();
            String tenKH = txtTenKh.getText();
            String sdt = txtSDT.getText();
            String email = txtMail.getText();
            String diem = txtDiem.getText();
            KhachHang_pojo kh = new KhachHang_pojo();
            kh.setMaKH(maKH);
            kh.setTenKH(tenKH);
            kh.setSdtKH(sdt);
            kh.setEmail(email);
            kh.setSoDiem(diem);
            if (txtMaKH.getText().isEmpty() || txtTenKh.getText().isEmpty() || txtSDT.getText().isEmpty() || txtMail.getText().isEmpty() || txtDiem.getText().isEmpty()) {
                txtMaKH.requestFocus();
                JOptionPane.showMessageDialog(this, "Không Được Để Trống Thông Tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (isChar(txtTenKh.getText())) {
                JOptionPane.showMessageDialog(this, " Tên Không Được Nhập Số ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (isNumeric(txtSDT.getText())) {
                JOptionPane.showMessageDialog(this, " SDT Không Được Nhập Chữ ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (isNumeric(diem)) {
                JOptionPane.showMessageDialog(this, " Diem Không Được Nhập Chữ ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (isEmail(email) == false) {
                JOptionPane.showMessageDialog(this, " Nhập Sai Định Dạng ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (isSDT(sdt) == false) {
                JOptionPane.showMessageDialog(this, " SDT Từ 10 Đến 11 SÔ ", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (KhachHang_dao.ktraMaKH(maKH) == true) {
                try {
                    KhachHang_dao.capNhatKhachHang(kh);
                    hienthiKH();
                    JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Cập Nhật Không Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                try {
                    KhachHang_dao.themKhachHang(kh);
                    hienthiKH();
                    JOptionPane.showMessageDialog(this, "Thêm Khách Hàng Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Thêm Khách Hàng  Không Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int row = tbKH.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Xóa ");
                return;
            } else {
                int n = JOptionPane.showConfirmDialog(this, "Chắc Xóa Chưa", "Thông Báo", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.NO_OPTION) {
                    return;
                } else {
                    String ma = (String) tbKH.getValueAt(row, 0);
                    KhachHang_dao.xoaKhachHang(ma);
                    hienthiKH();
                    JOptionPane.showMessageDialog(this, "Xoá Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            hienthiKH();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    public String kiemTraCapBacTheThanhVien(int soDiem) {
        if (soDiem <= 100) {
            return "Bạc";
        } else if (soDiem <= 500) {
            return "Vàng";
        }
        return "Kim cương";
    }

    private void btnXuatTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatTheActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String makh = txtMaKH.getText();
            FileWriter fw = new FileWriter("TheThanhVien_" + makh + ".txt");
            BufferedWriter bw = new BufferedWriter(fw);

            KhachHang_pojo kh = KhachHang_dao.layKhachHang(makh);
            String capBac = kiemTraCapBacTheThanhVien(Integer.parseInt(kh.getSoDiem()));

            bw.write("      THẺ THÀNH VIÊN");
            bw.newLine();
            bw.write("Cấp bậc: " + capBac);
            bw.newLine();
            bw.write("Mã KH: " + kh.getMaKH());
            bw.newLine();
            bw.write("Tên KH: " + kh.getTenKH());
            bw.newLine();
            bw.write("SĐT: " + kh.getSdtKH());
            bw.close();
            fw.close();

            JOptionPane.showMessageDialog(this, "Xuất thẻ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Xuất thẻ thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXuatTheActionPerformed

    private void btn_timKiemTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemTheoMaActionPerformed
        // TODO add your handling code here:
        txtTenKh.setEnabled(false);
        txtSDT.setEnabled(false);
        txtMail.setEnabled(false);
        txtDiem.setEnabled(false);
        txtMaKH.requestFocus();

        txtTenKh.setText("");
        txtSDT.setText("");
        txtMail.setText("");
        txtDiem.setText("");
        txtMaKH.setText("");
    }//GEN-LAST:event_btn_timKiemTheoMaActionPerformed

    private void btn_TraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraActionPerformed
        // TODO add your handling code here:
        String maKH = txtMaKH.getText();
        String tenKH = txtTenKh.getText();
        String sdt = txtSDT.getText();
        String email = txtMail.getText();
        String diem = txtDiem.getText();

        KhachHang_pojo kh = new KhachHang_pojo();
        kh.setMaKH(maKH);
        kh.setTenKH(tenKH);
        kh.setSdtKH(sdt);
        kh.setEmail(email);
        kh.setSoDiem(diem);
        try {
            if (maKH.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không Được Để Trống Mã Thông Tin Tìm Kiếm", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else if (KhachHang_dao.ktraMaKH(maKH) == true) {
                KhachHang_dao.layKhachHang(maKH);
                hienThiTheoMa();
                JOptionPane.showMessageDialog(this, "Tìm Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Bạn Nhập Sai Hoặc Không Có Thông Tin Khách Hàng Này", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_TraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatThe;
    private javax.swing.JButton btn_Tra;
    private javax.swing.JButton btn_timKiemTheoMa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbKH;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKh;
    private javax.swing.JTextField txt_capBac;
    // End of variables declaration//GEN-END:variables

    private void hienthiKH() {
        ArrayList<KhachHang_pojo> dsKH = KhachHang_dao.layDanhSachKhachHang();
        dtmKH.setRowCount(0);
        for (KhachHang_pojo pb : dsKH) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaKH());
            v.add(pb.getTenKH());
            v.add(pb.getSdtKH());
            v.add(pb.getEmail());
            v.add(pb.getSoDiem());
            dtmKH.addRow(v);
        }
        tbKH.setModel(dtmKH);
    }

    private void hienThiTheoMa() {
        String makh = txtMaKH.getText();
        ArrayList<KhachHang_pojo> dsKH = KhachHang_dao.layDanhSachKhachHangTheoMa(makh);
        dtmKH.setRowCount(0);
        for (KhachHang_pojo pb : dsKH) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaKH());
            v.add(pb.getTenKH());
            v.add(pb.getSdtKH());
            v.add(pb.getEmail());
            v.add(pb.getSoDiem());
            dtmKH.addRow(v);
        }
        tbKH.setModel(dtmKH);
    }

    public static boolean isNumeric(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }

    public static boolean isChar(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            } else {
                return true;
            }
        }
        return true;
    }

    public boolean isEmail(String s) {
        String EMAIL_REGEX = "^[A-Za-z0-9]+[A-Za-z0-9]*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)$";
        Boolean b = txtMail.getText().matches(EMAIL_REGEX);
        return b;
    }

    public boolean isSDT(String s) {
        String sdt = txtSDT.getText();
        if (sdt.length() < 12 && sdt.length() > 9) {
            return true;
        }
        return false;
    }
}
