/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import POJO.Const;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinhDN
 */
public class main_gui extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main_gui() {
        initComponents();
        JLabel bg;
        //  this.setSize(650, 550);
        this.setTitle("Quản lý cửa hàng bán sách");
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ImageIcon img = new ImageIcon("~~\\src\\background.jpg");
        bg = new JLabel("", img, JLabel.CENTER);
        bg.setBounds(0, 0, 3000, 700);
        this.add(bg);
        lbma.setText(Const.strUser);
        if(Const.strUser != null && Const.strPassword != null){
            mnuDangNhap.setVisible(false);
        }else{
            mnuDangNhap.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        lbma = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuNhanVien = new javax.swing.JMenuItem();
        mnuDangNhap = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mnuKhachHang = new javax.swing.JMenuItem();
        mnuSach = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenuItem();
        mnuPhieuNhap = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuDoanhThuNV = new javax.swing.JMenuItem();
        mnuTongThuKH = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPN.setMaximumSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hinhnen4.jpg"))); // NOI18N

        javax.swing.GroupLayout mainPNLayout = new javax.swing.GroupLayout(mainPN);
        mainPN.setLayout(mainPNLayout);
        mainPNLayout.setHorizontalGroup(
            mainPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPNLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPNLayout.setVerticalGroup(
            mainPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPNLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb.setText("Mã nhân viên:");

        lbma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        mnuHeThong.setText("Hệ thống");
        mnuHeThong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mnuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuNhanVien.setText("Nhân viên");
        mnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNhanVienActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuNhanVien);

        mnuDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuDangNhap.setText("Đăng nhập");
        mnuDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDangNhapMouseClicked(evt);
            }
        });
        mnuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangNhap);

        mnuDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangXuat);

        mnuThoat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mnuKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuKhachHang.setText("Khách hàng");
        mnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKhachHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuKhachHang);

        mnuSach.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuSach.setText("Sách");
        mnuSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSachActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuSach);

        mnuHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuHoaDon.setText("Hóa đơn");
        mnuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHoaDonActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuHoaDon);

        mnuPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuPhieuNhap.setText("Phiếu nhập");
        mnuPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPhieuNhapActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuPhieuNhap);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mnuDoanhThuNV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuDoanhThuNV.setText("Doanh thu nhân viên");
        mnuDoanhThuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoanhThuNVActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuDoanhThuNV);

        mnuTongThuKH.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mnuTongThuKH.setText("Tổng thu khách hàng");
        mnuTongThuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTongThuKHActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuTongThuKH);

        jMenuBar1.add(mnuThongKe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbma, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbma, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDangNhapMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuDangNhapMouseClicked

    private void mnuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangNhapActionPerformed
        // TODO add your handling code here:
        fDangNhap f = new fDangNhap(this, true);
        f.setVisible(true);
        this.mainPN.add(f);
    }//GEN-LAST:event_mnuDangNhapActionPerformed

    private void mnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKhachHangActionPerformed
        // TODO add your handling code here:
        try {
            KhachHang_gui f = new KhachHang_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuKhachHangActionPerformed

    private void mnuSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSachActionPerformed
        // TODO add your handling code here:
        try {
            Sach_gui f = new Sach_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuSachActionPerformed

    private void mnuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHoaDonActionPerformed
        // TODO add your handling code here:
        try {
            HoaDon_gui f = new HoaDon_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuHoaDonActionPerformed

    private void mnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNhanVienActionPerformed
        // TODO add your handling code here:
        try {
            NhanVien_gui f = new NhanVien_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuNhanVienActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        // TODO add your handling code here:
        Const.strUser = null;
        Const.strPassword = null;
        main_gui main = new main_gui();
        main.setVisible(false);
        this.dispose();
        fDangNhap f = new fDangNhap(this, true);
        f.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuDoanhThuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoanhThuNVActionPerformed
        // TODO add your handling code here:
        try {
            DoanhThuNV_gui f = new DoanhThuNV_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuDoanhThuNVActionPerformed

    private void mnuTongThuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTongThuKHActionPerformed
        // TODO add your handling code here:
        try {
            TongThuKH_gui f = new TongThuKH_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuTongThuKHActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không") == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPhieuNhapActionPerformed
        // TODO add your handling code here:
        try {
            PhieuNhap_gui f = new PhieuNhap_gui();
            f.setVisible(true);
            this.mainPN.removeAll();
            this.mainPN.add(f);
        } catch (Exception e) {
            if (Const.strUser == null && Const.strPassword == null) {
                JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập !!");
            } else {
                JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập !!");
            }
        }
    }//GEN-LAST:event_mnuPhieuNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbma;
    private javax.swing.JPanel mainPN;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoanhThuNV;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuHoaDon;
    private javax.swing.JMenuItem mnuKhachHang;
    private javax.swing.JMenuItem mnuNhanVien;
    private javax.swing.JMenuItem mnuPhieuNhap;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenuItem mnuSach;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenuItem mnuTongThuKH;
    // End of variables declaration//GEN-END:variables
}
