/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietPhieuNhap_dao;
import DAO.PhieuNhap_dao;
import DAO.Sach_dao;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import POJO.ChiTietPhieuNhap_pojo;
import POJO.PhieuNhap_pojo;
import POJO.Sach_pojo;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ThinhDN
 */
public class PhieuNhap_gui extends javax.swing.JInternalFrame {

    /**
     * Creates new form HoaDon
     */
    DefaultTableModel dtmPN = new DefaultTableModel();
    DefaultTableModel dtmCT = new DefaultTableModel();
    DefaultComboBoxModel s;

    public PhieuNhap_gui() {
        initComponents();
        this.setTitle("Phiếu nhập");
        initComponents();
        this.setSize(1920, 1080);
        String[] tieuDePN = {"Mã phiếu nhập", "Ngày nhập", "Tổng tiền", "Mã NV"};
        String[] tieuDeCT = {"Mã phiếu nhập", "Mã sách", "Số lượng"};
        dtmPN.setColumnIdentifiers(tieuDePN);
        dtmCT.setColumnIdentifiers(tieuDeCT);
        hienthiPN();
        hienthiCT();
        btnLuuHD.setEnabled(false);
        btnLuuCTHD.setEnabled(false);
        txtTongTien.setEnabled(false);
        loadCBOS();
        txtMaS.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnThemHD = new javax.swing.JButton();
        btnLuuHD = new javax.swing.JButton();
        btnXoaHD = new javax.swing.JButton();
        txtNgayNhap = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMaS = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        btnXoaCTHD = new javax.swing.JButton();
        btnLuuCTHD = new javax.swing.JButton();
        btnThemCTHD = new javax.swing.JButton();
        txtSoLuongM = new javax.swing.JSpinner();
        cboS = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPN = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCT = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1900, 1070));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("PHIẾU NHẬP");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN PHIẾU NHẬP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã phiếu nhập:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Ngày lập:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tổng Tiền :");

        btnThemHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThemHD.setText("Thêm");
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        btnLuuHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLuuHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luu.png"))); // NOI18N
        btnLuuHD.setText("Lưu");
        btnLuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHDActionPerformed(evt);
            }
        });

        btnXoaHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoaHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoaHD.setText("Xóa");
        btnXoaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHDActionPerformed(evt);
            }
        });

        txtNgayNhap.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaHD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtMaPN))
                        .addGap(192, 192, 192)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHD)
                    .addComponent(btnLuuHD)
                    .addComponent(btnXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT PHIẾU NHẬP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Mã Sách :");

        txtMaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label.setText("Số Lượng Mua :");

        btnXoaCTHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXoaCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        btnXoaCTHD.setText("Xóa");
        btnXoaCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTHDActionPerformed(evt);
            }
        });

        btnLuuCTHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLuuCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luu.png"))); // NOI18N
        btnLuuCTHD.setText("Lưu");
        btnLuuCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTHDActionPerformed(evt);
            }
        });

        btnThemCTHD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnThemCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them.png"))); // NOI18N
        btnThemCTHD.setText("Thêm");
        btnThemCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTHDActionPerformed(evt);
            }
        });

        txtSoLuongM.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cboS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cboS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSoLuongM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThemCTHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLuuCTHD)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaCTHD)))
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(txtSoLuongM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemCTHD)
                    .addComponent(btnLuuCTHD)
                    .addComponent(btnXoaCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tbPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPNMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbPN);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        tbCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(788, 788, 788)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        // TODO add your handling code here:
        txtMaPN.setText("");
        txtTongTien.setText("");
        txtMaPN.requestFocus();
        btnLuuHD.setEnabled(true);
    }//GEN-LAST:event_btnThemHDActionPerformed

    private void btnLuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHDActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy/MM/dd");
        String ngayNhap = formater.format(txtNgayNhap.getValue());
        if (txtMaPN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Được Để Trống Thông Tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (PhieuNhap_dao.ktraMaPN(txtMaPN.getText())) {
                boolean suaHD = PhieuNhap_dao.suaPN(txtMaPN.getText(), ngayNhap);
                if (suaHD) {
                    JOptionPane.showMessageDialog(this, "Sửa phiếu nhập thành công");
                    hienthiPN();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa phiếu nhập thất bại");
                }
            } else {
                boolean themHD = PhieuNhap_dao.themPN(txtMaPN.getText(), ngayNhap);
                if (themHD) {
                    JOptionPane.showMessageDialog(this, "Thêm phiếu nhập thành công");
                    hienthiPN();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm phiếu nhập thất bại");
                }
            }
            btnLuuHD.setEnabled(false);
        }
    }//GEN-LAST:event_btnLuuHDActionPerformed

    private void btnXoaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHDActionPerformed
        // TODO add your handling code here:
        try {
            int row = tbPN.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Xóa ");
                return;
            } else {
                int n = JOptionPane.showConfirmDialog(this,"Chắc Xóa Chưa", "Thông Báo", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.NO_OPTION) {
                    return;
                } else {
                    PhieuNhap_dao.xoaPN(txtMaPN.getText());
                    hienthiPN();
                    JOptionPane.showMessageDialog(this, "Xoá Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            hienthiPN();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaHDActionPerformed

    private void txtMaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSActionPerformed

    private void btnXoaCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTHDActionPerformed
        // TODO add your handling code here:
        try {
            int row = tbCT.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn Dòng Cần Xóa ");
                return;
            } else {
                int n = JOptionPane.showConfirmDialog(this,"Chắc Xóa Chưa" ,"Thông Báo", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.NO_OPTION) {
                    return;
                } else {
                    ChiTietPhieuNhap_dao.xoaCTPN(txtMaPN.getText(),txtMaS.getText());
                    hienthiPN();
                    hienthiCT();
                    JOptionPane.showMessageDialog(this, "Xoá Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            hienthiPN();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Liên Hệ Nhóm 1 Để Biết Thông Tin Chi Tiết", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaCTHDActionPerformed

    private void btnLuuCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTHDActionPerformed
        // TODO add your handling code here:
        if (txtMaPN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không Được Để Trống Thông Tin", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (ChiTietPhieuNhap_dao.ktraCTPN(txtMaPN.getText(), txtMaS.getText())) {
                ChiTietPhieuNhap_pojo ct = new ChiTietPhieuNhap_pojo(txtMaPN.getText(), txtMaS.getText(), Integer.parseInt(txtSoLuongM.getValue().toString()));
                boolean suaHD = ChiTietPhieuNhap_dao.suaCTPN(ct);
                if (suaHD) {
                    JOptionPane.showMessageDialog(this, "Sửa chi tiết phiếu nhập thành công");
                    hienthiCT();
                    hienthiPN();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa chi tiết phiếu nhập thất bại");
                }
            } else {
                ChiTietPhieuNhap_pojo ct = new ChiTietPhieuNhap_pojo(txtMaPN.getText(), txtMaS.getText(), Integer.parseInt(txtSoLuongM.getValue().toString()));
                boolean themHD = ChiTietPhieuNhap_dao.themCTPN(ct);
                if (themHD) {
                    JOptionPane.showMessageDialog(this, "Thêm chi tiết phiếu nhập thành công");
                    hienthiCT();
                     hienthiPN();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm chi tiết phiếu nhập thất bại");
                }
            }
            btnLuuHD.setEnabled(false);
        }
    }//GEN-LAST:event_btnLuuCTHDActionPerformed

    private void btnThemCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTHDActionPerformed
        // TODO add your handling code here:
        txtMaS.setText("");
        txtMaS.requestFocus();
        btnLuuCTHD.setEnabled(true);
    }//GEN-LAST:event_btnThemCTHDActionPerformed

    private void tbPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPNMouseClicked
        // TODO add your handling code here:
        btnLuuHD.setEnabled(true);
        int row = tbPN.getSelectedRow();
        txtMaPN.setText((String) String.valueOf(tbPN.getValueAt(row, 0)));
        //txtNgayNhap.setValue((String) String.valueOf(tbPN.getValueAt(row, 1)));
        txtTongTien.setText((String) String.valueOf(tbPN.getValueAt(row, 2)));
        hienthiCT();
    }//GEN-LAST:event_tbPNMouseClicked

    private void tbCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCTMouseClicked
        // TODO add your handling code here:
        btnLuuCTHD.setEnabled(true);
        int row = tbCT.getSelectedRow();
        txtMaS.setText((String) String.valueOf(tbCT.getValueAt(row, 1)));
        txtSoLuongM.setValue(Integer.parseInt(String.valueOf(tbCT.getValueAt(row, 2))));
    }//GEN-LAST:event_tbCTMouseClicked

    private void cboSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSActionPerformed
        // TODO add your handling code here:
        int row = cboS.getSelectedIndex();
        txtMaS.setText(cboS.getItemAt(row));
    }//GEN-LAST:event_cboSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuCTHD;
    private javax.swing.JButton btnLuuHD;
    private javax.swing.JButton btnThemCTHD;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnXoaCTHD;
    private javax.swing.JButton btnXoaHD;
    private javax.swing.JComboBox<String> cboS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label;
    private javax.swing.JTable tbCT;
    private javax.swing.JTable tbPN;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtMaS;
    private javax.swing.JSpinner txtNgayNhap;
    private javax.swing.JSpinner txtSoLuongM;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void hienthiPN() {
        ArrayList<PhieuNhap_pojo> dsPN = PhieuNhap_dao.layDanhSachPhieuNhap();
        dtmPN.setRowCount(0);
        for (PhieuNhap_pojo pb : dsPN) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaPhieuNhap());
            v.add(pb.getNgayNhap());
            v.add(pb.getTongTien());
            v.add(pb.getMaNV());
            dtmPN.addRow(v);
        }
        tbPN.setModel(dtmPN);
    }

    private void hienthiCT() {
        ArrayList<ChiTietPhieuNhap_pojo> dsPN = ChiTietPhieuNhap_dao.layDanhSachCTPhieuNhap(txtMaPN.getText());
        dtmCT.setRowCount(0);
        for (ChiTietPhieuNhap_pojo pb : dsPN) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaPhieuNhap());
            v.add(pb.getMaSach());
            v.add(pb.getSoLuong());
            dtmCT.addRow(v);
        }
        tbCT.setModel(dtmCT);
    }

    private void loadCBOS() {
        s = (DefaultComboBoxModel) cboS.getModel();
        ArrayList<Sach_pojo> dsKH = Sach_dao.layDanhSachSach();
        for (Sach_pojo pb : dsKH) {
            cboS.addItem(pb.getMaS());
        }
    }
}
