/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.SQLServerDataProvider;
import DAO.Sach_dao;
import DAO.TacGia_dao;
import DAO.TheLoai_dao;
import POJO.MyCombobox;
import POJO.Sach_pojo;
import POJO.TacGia_pojo;
import POJO.TheLoai_pojo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThinhDN
 */
public class TimSach_gui extends javax.swing.JDialog {

    /**
     * Creates new form TimSach_gui
     */
    DefaultComboBoxModel tl;
    DefaultComboBoxModel tg;
    DefaultTableModel dtmS = new DefaultTableModel();
    String MaS = null; 
    public TimSach_gui() {
        this.setTitle("Tìm sách");
        initComponents();
        loadTacGia();
        loadTheLoai();
        String[] tieuDeS = {"Mã sách", "Tên sách", "Đơn giá", "Số lượng còn", "Mã TG", "Mã TL"};
        dtmS.setColumnIdentifiers(tieuDeS);
        hienthi();
        txtMaS.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaS = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        txtTenS = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboTacGia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboTheLoai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("TÌM SÁCH");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mã Sách :");

        txtMaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label.setText("Tên sách :");

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/timkiem.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tác giả");

        cboTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTacGiaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thể loại");

        cboTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTheLoaiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboTheLoaiMousePressed(evt);
            }
        });
        cboTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTheLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTim))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label)
                            .addComponent(txtTenS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim)
                            .addComponent(jLabel7)
                            .addComponent(cboTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach_pojo> dsS = Sach_dao.layDanhSachSachTheoTen(txtTenS.getText().toString());
        dtmS.setRowCount(0);
        for (Sach_pojo pb : dsS) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaS());
            v.add(pb.getTenS());
            v.add(pb.getDonGia());
            v.add(pb.getSlCon());
            v.add(pb.getMaTG());
            v.add(pb.getMaTL());
            dtmS.addRow(v);
        }
        tbS.setModel(dtmS); 
    }//GEN-LAST:event_btnTimActionPerformed

    private void cboTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTheLoaiMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboTheLoaiMouseClicked

    private void cboTheLoaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTheLoaiMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboTheLoaiMousePressed

    private void cboTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTheLoaiActionPerformed
        // TODO add your handling code here:
        MyCombobox chon = (MyCombobox) tl.getSelectedItem();
        String maLoai = chon.MaString();
        ArrayList<Sach_pojo> dsS = Sach_dao.layDanhSachSachTheoTL(maLoai);
        dtmS.setRowCount(0);
        for (Sach_pojo pb : dsS) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaS());
            v.add(pb.getTenS());
            v.add(pb.getDonGia());
            v.add(pb.getSlCon());
            v.add(pb.getMaTG());
            v.add(pb.getMaTL());
            dtmS.addRow(v);
        }
        tbS.setModel(dtmS);
    }//GEN-LAST:event_cboTheLoaiActionPerformed

    private void cboTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTacGiaActionPerformed
        // TODO add your handling code here:
        MyCombobox chon = (MyCombobox) tg.getSelectedItem();
        String maTG = chon.MaString();
        ArrayList<Sach_pojo> dsS = Sach_dao.layDanhSachSachTheoTG(maTG);
        dtmS.setRowCount(0);
        for (Sach_pojo pb : dsS) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaS());
            v.add(pb.getTenS());
            v.add(pb.getDonGia());
            v.add(pb.getSlCon());
            v.add(pb.getMaTG());
            v.add(pb.getMaTL());
            dtmS.addRow(v);
        }
        tbS.setModel(dtmS);
    }//GEN-LAST:event_cboTacGiaActionPerformed

    private void tbSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSMouseClicked
        // TODO add your handling code here:  
        int row = tbS.getSelectedRow();
        txtMaS.setText((String) String.valueOf(tbS.getValueAt(row, 0)));
    }//GEN-LAST:event_tbSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimSach_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimSach_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimSach_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimSach_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TimSach_gui dialog = new TimSach_gui();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboTacGia;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable tbS;
    private javax.swing.JTextField txtMaS;
    private javax.swing.JTextField txtTenS;
    // End of variables declaration//GEN-END:variables

    private void loadTheLoai() {
        tl = (DefaultComboBoxModel) cboTheLoai.getModel();
        ArrayList<TheLoai_pojo> dsKH = TheLoai_dao.layDanhSachTheLoai();
        for (TheLoai_pojo pb : dsKH) {
            MyCombobox v = new MyCombobox(pb.getMaTL(), pb.getTenTL());
            tl.addElement(v);
        }
    }

    private void loadTacGia() {
        tg = (DefaultComboBoxModel) cboTacGia.getModel();
        ArrayList<TacGia_pojo> ds = TacGia_dao.layDanhSachTacGia();
        tg.removeAllElements();
        for (TacGia_pojo pb : ds) {
            MyCombobox v = new MyCombobox(pb.getMaTG(), pb.getTenTG());
            tg.addElement(v);
        }
    }

    private void hienthi() {
        ArrayList<Sach_pojo> dsS = Sach_dao.layDanhSachSach();
        dtmS.setRowCount(0);
        for (Sach_pojo pb : dsS) {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getMaS());
            v.add(pb.getTenS());
            v.add(pb.getDonGia());
            v.add(pb.getSlCon());
            v.add(pb.getMaTG());
            v.add(pb.getMaTL());
            dtmS.addRow(v);
        }
        tbS.setModel(dtmS);
    }

}
