/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.TongThuKH_dao;
import POJO.TongThuKH_pojo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class TongThuKH_gui extends javax.swing.JInternalFrame {

    /**
     * Creates new form TongThuKH_gui
     */
    DefaultTableModel dtmTT = new DefaultTableModel();

    public TongThuKH_gui() {
        this.setTitle("Tổng thu khách hàng");
        initComponents();
        this.setSize(1920, 1080);
        spFromDate.setEnabled(false);
        spToDate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTongThu = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spFromDate = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spToDate = new javax.swing.JSpinner();
        btnThongKeTongThuKH = new javax.swing.JButton();
        cbDieuKien = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        tbTongThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTongThu);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("THỐNG KÊ TỔNG THU CỦA KHÁCH HÀNG");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Từ ngày:");

        spFromDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spFromDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1682355600000L), new java.util.Date(1640970000000L), new java.util.Date(1682442000000L), java.util.Calendar.DAY_OF_MONTH));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("đến ngày:");

        spToDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spToDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1682442000000L), new java.util.Date(1640970000000L), new java.util.Date(1682442000000L), java.util.Calendar.DAY_OF_MONTH));

        btnThongKeTongThuKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThongKeTongThuKH.setText("Thống kê");
        btnThongKeTongThuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeTongThuKHActionPerformed(evt);
            }
        });

        cbDieuKien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbDieuKien.setText("Có điều kiện");
        cbDieuKien.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbDieuKienStateChanged(evt);
            }
        });
        cbDieuKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDieuKienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDieuKien)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThongKeTongThuKH)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKeTongThuKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDieuKien)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/doanhthu.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeTongThuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeTongThuKHActionPerformed
        // TODO add your handling code here:
        String[] tieuDeTT = {"Mã khách hàng", "Tên khách hàng", "Tổng thu"};
        dtmTT.setColumnIdentifiers(tieuDeTT);
        hienthiTT();
    }//GEN-LAST:event_btnThongKeTongThuKHActionPerformed

    private void hienthiTT() {
        try {
            SimpleDateFormat formater = new SimpleDateFormat("yyyy/MM/dd");
            String fromDate = formater.format(spFromDate.getValue());
            String toDate = formater.format(spToDate.getValue());
            ArrayList<TongThuKH_pojo> dsTT;
            if (cbDieuKien.isSelected()) {
                dsTT = TongThuKH_dao.layDanhSachTongThuKHTheoNgay(fromDate, toDate);
            } else {
                dsTT = TongThuKH_dao.layDanhSachTongThuKH();
            }
            dtmTT.setRowCount(0);
            for (TongThuKH_pojo tt : dsTT) {
                Vector<Object> v = new Vector<Object>();
                v.add(tt.getMaKH());
                v.add(tt.getTenKH());
                v.add(tt.getTongThu());
                dtmTT.addRow(v);
            }
            tbTongThu.setModel(dtmTT);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Bạn không có quyền thống kê", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void cbDieuKienStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbDieuKienStateChanged
        // TODO add your handling code here:
        if (cbDieuKien.isSelected()) {
            spFromDate.setEnabled(true);
            spToDate.setEnabled(true);
        } else {
            spFromDate.setEnabled(false);
            spToDate.setEnabled(false);
        }
    }//GEN-LAST:event_cbDieuKienStateChanged

    private void cbDieuKienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDieuKienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDieuKienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKeTongThuKH;
    private javax.swing.JCheckBox cbDieuKien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spFromDate;
    private javax.swing.JSpinner spToDate;
    private javax.swing.JTable tbTongThu;
    // End of variables declaration//GEN-END:variables

}
